left_camera_config: "config/camera_cal/Left_Air.xml"
right_camera_config: "config/camera_cal/Right_Air.xml"
left_folder: "CalibrationImgs/Good_StereoAir/Left/"
right_folder: "CalibrationImgs/Good_StereoAir/Right/"
baseline: 120  # mm
